language: scala
scala:
  - 2.12.7

before_install:
  - export DISPLAY=:0.0
  - sh -e /etc/init.d/xvfb start

script:
  - sbt clean coverage test coverageReport

after_success:
  - sbt coverageReport coveralls